# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Owner       = "demo-cluster"
      Environment = "dev"
      Tenant      = "DC"
    }
  }
}
