repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        exclude: modules
      - id: terraform_validate
        exclude: docs
      # - id: terraform_tfsec
      #   files: ^examples/ # only scan `examples/*` which are the implementation
      #   args:
      #     - --args=--config-file=__GIT_WORKING_DIR__/tfsec.yaml
      #     - --args=--concise-output
