# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tf-demo-cluster-bucket-138904756338"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-1"
  }
}
