# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "my-terraform-state-bkc"
    encrypt = true
    key     = "dev/vpc/terraform.tfstate"
    region  = "us-east-1"
  }
}
